name: "Cachix"
on:
  workflow_dispatch: # allows manual triggering from the Actions UI
  push:
    branches:
      - main
jobs:
  Cachix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: dscv101

        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Setting up packages..."
      run: |
          nix profile install nixpkgs#nix-fast-build # parallel nix builder
    
    - run: nix-fast-build
    - run: nix-shell --run "echo OK"